import "./globals.css";
import { Montserrat } from "next/font/google";

import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import { useState } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <NavBar />
        <div className="">
          <div>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
