import Footer from "./components/Footer";
import NavBar from "./components/NavBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
